coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        enabled: true

flags:
  website:
    carryforward: true
  package-2:
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
